# Generated by Django 5.2.3 on 2025-06-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A descriptive title for the order.', max_length=255)),
                ('status', models.CharField(default='in_progress', help_text="The current status of the order (e.g., 'in_progress', 'completed', 'cancelled').", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='The total price for the order. Using DecimalField to avoid floating-point inaccuracies with currency.', max_digits=10)),
                ('revisions', models.IntegerField(default=3, help_text='The number of revisions included in the offer.')),
                ('delivery_time_in_days', models.IntegerField(default=5, help_text='The agreed-upon delivery time in days.')),
                ('features', models.JSONField(default=list, help_text='A list of features or specific items included in the order, stored as JSON.')),
                ('offer_type', models.CharField(default='basic', help_text="The type of package or offer this order is based on (e.g., 'basic', 'premium').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the record was first created. Automatically set on creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp for when the record was last updated. Automatically set on every save.')),
                ('business_user', models.ForeignKey(help_text='The user who is selling the service/product (the business/freelancer).', on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(help_text='The user who is buying the service/product (the customer).', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
