# Generated by Django 5.2.3 on 2025-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=3),
        ),
    ]
