# Generated by Django 5.2.3 on 2025-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_delivery_time_in_days_alter_order_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_type',
            field=models.CharField(default='basic', max_length=50),
        ),
    ]
