# Generated by Django 5.2.3 on 2025-06-26 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_order_offer_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(help_text='The user who is selling the service/product (the business/freelancer).', on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the record was first created. Automatically set on creation.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(help_text='The user who is buying the service/product (the customer).', on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.IntegerField(default=5, help_text='The agreed-upon delivery time in days.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list, help_text='A list of features or specific items included in the order, stored as JSON.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(default='basic', help_text="The type of package or offer this order is based on (e.g., 'basic', 'premium').", max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The total price for the order. Using DecimalField to avoid floating-point inaccuracies with currency.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=3, help_text='The number of revisions included in the offer.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='in_progress', help_text="The current status of the order (e.g., 'in_progress', 'completed', 'cancelled').", max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(help_text='A descriptive title for the order.', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for when the record was last updated. Automatically set on every save.'),
        ),
    ]
