# Generated by Django 5.2.3 on 2025-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offer_offerdetail_delete_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
