# Generated by Django 5.2.3 on 2025-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_offerdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/images/'),
        ),
    ]
