# Generated by Django 5.2.3 on 2025-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_offerdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
