# Generated by Django 5.2.3 on 2025-06-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_offerdetail_features_offerdetail_offer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetail',
            old_name='delivery_time_days',
            new_name='delivery_time_in_days',
        ),
    ]
