# Generated by Django 5.2.3 on 2025-06-30 05:50

import django.db.models.deletion
import profile_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to=profile_app.models.user_directory_path, verbose_name='Profilbild')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Standort')),
                ('tel', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefonnummer')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('working_hours', models.CharField(blank=True, default='', max_length=50, verbose_name='Öffnungszeiten')),
                ('type', models.CharField(choices=[('customer', 'Kunde'), ('business', 'Geschäft')], default='customer', max_length=10, verbose_name='Benutzertyp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
